import { useState } from "react";
import {
  Button,
  ErrorState,
  Input,
  LoadingState,
  PageHeader,
  useFetch,
  useTenantContext,
} from "@core-labs/admin-shell";
import {
  fetchSeoHealth,
  fetchSeoPolicies,
  previewUrlPolicy,
  upsertSeoPolicy,
} from "../lib/api";

export function SeoMetaPage() {
  const ctx = useTenantContext();
  const scopeType = ctx.regionCode ? "region" : "brand";
  const scopeId = ctx.regionCode ?? ctx.brandId ?? "default";
  const data = useFetch(() => fetchSeoPolicies(scopeType, scopeId));
  const [titleTemplate, setTitleTemplate] = useState("{city_name} News | {brand}");
  const [descTemplate, setDescTemplate] = useState("");
  const [saving, setSaving] = useState(false);

  const existing = data.data?.items?.[0];

  const handleSave = async () => {
    setSaving(true);
    try {
      await upsertSeoPolicy({
        scope_type: scopeType,
        scope_id: scopeId,
        title_template: titleTemplate,
        description_template: descTemplate || undefined,
      });
      data.refetch();
    } finally {
      setSaving(false);
    }
  };

  if (data.loading) return <LoadingState />;
  if (data.error) return <ErrorState message={data.error} onRetry={data.refetch} />;

  return (
    <>
      <PageHeader title="Meta Templates" description="Policy-based SEO — not per-page CRUD" />
      <div className="max-w-xl space-y-4 rounded-xl border p-4">
        <div>
          <label className="text-sm text-muted-foreground">Title template</label>
          <Input
            className="mt-1"
            value={existing?.title_template ?? titleTemplate}
            onChange={(e) => setTitleTemplate(e.target.value)}
            placeholder="{city_name} News | {brand}"
          />
        </div>
        <div>
          <label className="text-sm text-muted-foreground">Description template</label>
          <Input
            className="mt-1"
            value={existing?.description_template ?? descTemplate}
            onChange={(e) => setDescTemplate(e.target.value)}
          />
        </div>
        <Button onClick={handleSave} disabled={saving}>
          {saving ? "Saving…" : "Save policy"}
        </Button>
      </div>
    </>
  );
}

export function SeoHreflangPage() {
  const ctx = useTenantContext();
  return (
    <>
      <PageHeader title="hreflang" description="Locale ↔ alternate URL mapping" />
      {ctx.selectedRegion ? (
        <dl className="rounded-xl border p-4 text-sm">
          <div className="grid gap-2 sm:grid-cols-2">
            <div>
              <dt className="text-muted-foreground">Region</dt>
              <dd>{ctx.selectedRegion.city_code}</dd>
            </div>
            <div>
              <dt className="text-muted-foreground">hreflang locales</dt>
              <dd>{ctx.locale ?? ctx.selectedRegion.target_language}</dd>
            </div>
          </div>
        </dl>
      ) : (
        <p className="text-muted-foreground">Select a region in the context bar.</p>
      )}
    </>
  );
}

export function SeoSitemapPage() {
  return (
    <>
      <PageHeader title="Sitemap Policy" description="Generated at build time from policy rules" />
      <p className="text-sm text-muted-foreground">
        Sitemap entries are generated by the SSG builder (100k+/day). Configure changefreq and priority in SEO meta policies.
      </p>
    </>
  );
}

export function SeoUrlPreviewPage() {
  const ctx = useTenantContext();
  const [slug, setSlug] = useState("sample-article");
  const [result, setResult] = useState<{ canonical_url: string; hreflang_urls?: Record<string, string> } | null>(null);
  const [loading, setLoading] = useState(false);

  const handlePreview = async () => {
    setLoading(true);
    try {
      const res = await previewUrlPolicy({
        apex_domain: ctx.selectedBrand?.apex_domain ?? "example.com",
        slug,
      });
      setResult(res);
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <PageHeader title="URL Policy Preview" description="Canonical and hreflang URL generation" />
      <div className="flex max-w-lg gap-2">
        <Input value={slug} onChange={(e) => setSlug(e.target.value)} placeholder="slug" />
        <Button onClick={handlePreview} disabled={loading}>
          Preview
        </Button>
      </div>
      {result && (
        <div className="mt-4 rounded-xl border p-4 text-sm">
          <p>
            <span className="text-muted-foreground">Canonical:</span> {result.canonical_url}
          </p>
          {result.hreflang_urls && (
            <ul className="mt-2 space-y-1">
              {Object.entries(result.hreflang_urls).map(([loc, url]) => (
                <li key={loc}>
                  {loc}: {url}
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </>
  );
}

export function SeoHealthPage() {
  const ctx = useTenantContext();
  const data = useFetch(() =>
    fetchSeoHealth(ctx.brandId ?? undefined, ctx.regionCode ?? undefined),
  );

  if (data.loading) return <LoadingState />;
  if (data.error) return <ErrorState message={data.error} onRetry={data.refetch} />;

  return (
    <>
      <PageHeader title="SEO Health" description="Policy and hreflang checklist" />
      <p className="mb-4 text-2xl font-bold">Score: {data.data?.score ?? 0}</p>
      <ul className="space-y-2">
        {(data.data?.checks ?? []).map((c) => (
          <li key={c.id} className="flex items-center gap-2 rounded-lg border px-4 py-2 text-sm">
            <span className={c.status === "ok" ? "text-green-600" : "text-amber-600"}>{c.status}</span>
            {c.label}
          </li>
        ))}
      </ul>
    </>
  );
}
